---
apiVersion: v1
data:
  apiToken: ZHQwYzAxLlVHMkpOUEhIV0tZSlhQNTdHNzZNSzRWVC40VTVPVjdYUllRRVpDRElMS1U1RFVVUzdaVUdYRjZYNzVER1I3TU5LTFpCM1M3U1FJMjM3QVBVWEpVMjREQjRK
  dataIngestToken: ZHQwYzAxLldGSzczWlBRS0g1TElGRktMS1FFSzZCNy5XQk43U1dVR1BGR01XV0o3QVdKSlJGVTdLU1g3RE5VQVNBTFlZUUVVSTM1VDNBRUJBTkVDSUZSMkxTWlVETktU
kind: Secret
metadata:
  name: video-otthub-dev
  namespace: dynatrace
type: Opaque

---
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: video-otthub-dev
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/activegate-authtoken: "true"
spec:
  apiUrl: https://gxk996.dynatrace-managed.com:9999/e/631b553f-73c8-49ed-9e11-85f7ad7a8acc/api
  skipCertCheck: false
  networkZone: video-otthub-dev
  enableIstio: true
  oneAgent:
    classicFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "false"
      args:
        - --set-host-group=video-otthub-dev
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
    nodeSelector: null
    agentpool: vdootthubdev
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
    group: video-otthub-dev
